LaptopShop/Controllers/LaptopController.cs
using LaptopShop.CQRS.Queries;
using LaptopShop.Models.database;
using LaptopShop.Models.servive;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace LaptopShop.Controllers
{
    [Authorize]
    public class LaptopController : Controller
    {
        private readonly IMediator mediator;
        ILogger<LaptopController> _logger;
        IMemoryCache _Cache;
		public LaptopController( ILogger<LaptopController> logger, IMemoryCache cache, IMediator mediator)
		{
			_logger = logger;
			_Cache = cache;
			this.mediator = mediator;
		}

		public async Task< IActionResult> Index()
        {
            string key = "GetAllLaptops";
            if (_Cache.TryGetValue(key, out List<Laptop> data))
            {
                _logger.LogInformation("found in the cache");
                return View(data);

            }
           
            
            var cacheOptions = new MemoryCacheEntryOptions()
            .SetSlidingExpiration(TimeSpan.FromMinutes(5))
            .SetAbsoluteExpiration(TimeSpan.FromMinutes(30))
            .SetPriority(CacheItemPriority.Normal);
            data = await mediator.Send(new GetAllLaptopsQuery());
            _Cache.Set(key, data, cacheOptions);
            
            
            _logger.LogInformation("Not found in the cache");
            
            
            return View(data);
        }







        public async Task<IActionResult> gitbyid(int Id)
        {
			return  View(await mediator.Send(new GetLaptopByIdQuery(Id)));
		}

        public async Task<IActionResult> getcatagory(String catagory)
        {
            string key = "Catagorty" + catagory;
            if (_Cache.TryGetValue(key, out List<Laptop> data))
            {
                _logger.LogInformation("found in the cache");
                return View("Index", data);

            }
            
            var cacheOptions = new MemoryCacheEntryOptions()
            .SetSlidingExpiration(TimeSpan.FromMinutes(5))
            .SetAbsoluteExpiration(TimeSpan.FromMinutes(30))
            .SetPriority(CacheItemPriority.Normal);
            data = await mediator.Send(new GetLaptopsByCategorieQuery(catagory));
            _Cache.Set(key, data, cacheOptions);
            
            
            _logger.LogInformation("Not found in the cache");
            
            
            
            return View("Index", data);
        }


    }
}

LaptopShop/Views/Shared/_Layout.cshtml
@User
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - LaptopShop</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/LaptopShop.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LaptopShop</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Laptop" asp-action="Index">ShowLaptop</a>
						</li>
					</ul>
					<ul class="navbar-nav">
						@if (User.Identity.IsAuthenticated == false)
						{
							<li class="navbar-nav">
								<a class="nav-link text-dark" asp-controller="User" asp-action="login"> login</a>
							</li>
							<li class="navbar-nav">
								<a class="nav-link text-dark" asp-controller="User" asp-action="Register"> Register</a>
							</li>
						}
						@if (User.Identity.IsAuthenticated == true)
						{

							<li class="navbar-nav">
								<a class="nav-link text-dark" href="#"> @User.Identity.Name</a>
							</li>
							<li class="navbar-nav">
								<a class="nav-link text-dark" href="/Chat/Index"> Chat</a>
							</li>

							<li class="navbar-nav">
								<a class="nav-link text-dark" asp-controller="User" asp-action="logout"> logout</a>
							</li>
							<li class="navbar-nav">
								<a class="nav-link text-dark" onclick="window.location = '/Cart/viewCart/0/@User.Identity.Name'"> viewCart</a>
							</li>

						}



					</ul>

				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - LaptopShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>